### ISSUE TITLE
数据库导入错误

### ISSUE THREAD

**Issue by dhm123** [Frodez/BlogManagePlatform#1]
大佬  报这错  [Err] 1273 - Unknown collation: 'utf8mb4_0900_ai_ci'   我查了一下  说是数据库字符集错误  我看你用的是SET NAMES utf8mb4;     我建数据库的时候选的也是utf8mb4   但是还是报错了耶

**Comment by Frodez** [comment]
> 大佬 报这错 [Err] 1273 - Unknown collation: 'utf8mb4_0900_ai_ci' 我查了一下 说是数据库字符集错误 我看你用的是SET NAMES utf8mb4; 我建数据库的时候选的也是utf8mb4 但是还是报错了耶

你的mysql版本是多少呢？我的mysql版本是社区版的8.0.13。
在社区版下,新建数据库时,请选择字符集为utf8mb4,排序规则为utf8mb4_0900_ai_ci。
如果仍然出现问题，请描述得更具体一些，我尽量帮忙解决。
最后，我也不是大佬，也只是一个学习者罢了，一起学习，一起进步。
