### ISSUE TITLE
如果做集群的话，怎么让TokenCache同步呢

### ISSUE THREAD

**Issue by GroganflyOver** [Frodez/BlogManagePlatform#44]
你的项目里没使用session，用了自定义map替代，想了解一下集群怎么处理，谢谢

**Comment by GroganflyOver** [comment]
`@GetMapping(value = "/availables", name = "查询可用定时任务接口")
	@ApiResponses(value = { @ApiResponse(code = 200, message = "成功", response = AvailableTaskInfo.class) })
	public Result getAvailableTasks(@RequestBody QueryPage param) {
		return taskService.getAvailableTasks(param);
	}`

还有几个方法中申明的是get方法,参数用了@requestBody 
用swagger，发请求时报错
`TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.`

这类方法应该用PostMapping

**Comment by Frodez** [comment]
> `@GetMapping(value = "/availables", name = "查询可用定时任务接口") @ApiResponses(value = { @ApiResponse(code = 200, message = "成功", response = AvailableTaskInfo.class) }) public Result getAvailableTasks(@RequestBody QueryPage param) { return taskService.getAvailableTasks(param); }`
> 
> 还有几个方法中申明的是get方法,参数用了@requestbody
> 用swagger，发请求时报错
> `TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.`
> 
> 这类方法应该用PostMapping

TokenCache是实现了ICache接口的，ICache接口也可以用Redis来实现的呢。
GetMapping那个确实是写错了的缘故。
